package View.schedule_generation;

import Model.Queries;
import Model.Reset;
import static View.Alerts.alert;
import static View.MainFrame.first_panel1;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class excel_file_panel extends javax.swing.JPanel {

    public excel_file_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        excel_file_next_btn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("upload excel file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 320, 70));

        jLabel106.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(0, 102, 153));
        jLabel106.setText("file name (when uploaded)  and confirmation message");
        add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 410, 50));

        jLabel107.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 102, 153));
        jLabel107.setText("upload excel file for student registration, programs and semesters:");
        add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 540, 40));

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(0, 102, 153));
        jLabel108.setText("Student Course Registration Panel:");
        add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 26, 350, 40));

        excel_file_next_btn.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        excel_file_next_btn.setForeground(new java.awt.Color(0, 102, 153));
        excel_file_next_btn.setText("-->");
        excel_file_next_btn.setToolTipText("Logo");
        excel_file_next_btn.setAlignmentX(0.5F);
        excel_file_next_btn.setAutoscrolls(true);
        excel_file_next_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excel_file_next_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                excel_file_next_btnMouseEntered(evt);
            }
        });
        add(excel_file_next_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 70, 60));
    }// </editor-fold>//GEN-END:initComponents


    private void excel_file_next_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excel_file_next_btnMouseClicked
        this.setVisible(false);
        first_panel1.setVisible(true);
    }//GEN-LAST:event_excel_file_next_btnMouseClicked

    private void excel_file_next_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excel_file_next_btnMouseEntered

    }//GEN-LAST:event_excel_file_next_btnMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean uploaded = Reset.studentFileUploaded();
        if (uploaded) {
            int choice = JOptionPane.showConfirmDialog(null, "Student file already uploaded. Continue will replace previous data");
            if (choice == 0) {
                Reset.resetStudents();
                JFileChooser chooser = new JFileChooser("/");
                int f = chooser.showSaveDialog(null);
                if (f == JFileChooser.APPROVE_OPTION) {
                    String file = chooser.getSelectedFile().getAbsolutePath();
                    String[] split = file.split(".");
                    String extension = split[split.length - 1];
                    if (!extension.equalsIgnoreCase("csv")) {
                        alert("Please select a .csv file");
                        return;
                    }
                    System.out.println(file);
                    File file2 = new File(file);
                    JOptionPane.showMessageDialog(null, "It might take a while. Please have patient");
                    Queries.addStudentsToDB(file2);
                    Queries.assignSectionToStudents(1);
                    Queries.createInitialStudentSchedule();
                    Reset.uploadStudentFile(1);
                }
                JOptionPane.showMessageDialog(null, "File uploaded successfuly!");
                Reset.uploadStudentFile(1);
            } else {
                alert("File not uploaded");
            }
        } else {
            Reset.resetStudents();
            JFileChooser chooser = new JFileChooser("/");
            int f = chooser.showSaveDialog(null);
            if (f == JFileChooser.APPROVE_OPTION) {
                String file = chooser.getSelectedFile().getAbsolutePath();
//                String[] split = file.split(".");
//                String extension = split[split.length - 1];
//                System.out.println(file);
//                if (!extension.equalsIgnoreCase("csv")) {
//                    alert("Please select a .csv file");
//                    return;
//                }
                System.out.println(file);
                File file2 = new File(file);
                JOptionPane.showMessageDialog(null, "It might take a while. Please have patient");
                Queries.addStudentsToDB(file2);
                Queries.assignSectionToStudents(1);
                Queries.createInitialStudentSchedule();
                Reset.uploadStudentFile(1);
            }
            JOptionPane.showMessageDialog(null, "File uploaded successfuly!");
            Reset.uploadStudentFile(1);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel excel_file_next_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    // End of variables declaration//GEN-END:variables
}
