package View.schedule_generation;

import Model.Queries;
import Model.Reset;
import static View.Alerts.alert;
import static View.MainFrame.first_panel1;
import static View.MainFrame.final_panel1;
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class excel_file_panel extends javax.swing.JPanel {

    public excel_file_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 50, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Upload CSV File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 320, 70));

        jLabel107.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(0, 102, 153));
        jLabel107.setText("2)    Uploading File Can Take Few Mintues");
        add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 540, 50));

        jLabel108.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel108.setForeground(new java.awt.Color(255, 255, 255));
        jLabel108.setText("S t u d e n t   C o u r s e   R e g i s t r a t i o n   P a n e l");
        add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 620, 70));

        next.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        next.setForeground(new java.awt.Color(0, 102, 153));
        next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next.setText("N e x t ->");
        next.setToolTipText("Logo");
        next.setAlignmentX(0.5F);
        next.setAutoscrolls(true);
        next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 200, 60));

        jLabel109.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(0, 102, 153));
        jLabel109.setText("1)    Upload Student Registration File In .csv Format");
        add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 540, 50));
    }// </editor-fold>//GEN-END:initComponents


    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        this.setVisible(false);
        final_panel1.setVisible(true);
    }//GEN-LAST:event_nextMouseClicked

    private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
        next.setBackground(new Color(0, 102, 153));
        next.setForeground(new Color(250, 250, 250));
    }//GEN-LAST:event_nextMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean uploaded = Reset.studentFileUploaded();
        if (uploaded) {
            int choice = JOptionPane.showConfirmDialog(null, "Student file already uploaded. Continue will replace previous data");
            if (choice == 0) {
                Reset.resetStudents();
                JFileChooser chooser = new JFileChooser("/");
                int f = chooser.showSaveDialog(null);
                if (f == JFileChooser.APPROVE_OPTION) {
                    String file = chooser.getSelectedFile().getAbsolutePath();
                    File file2 = new File(file);
                    JOptionPane.showMessageDialog(null, "It might take a while. Please have patient");
                    Queries.addStudentsToDB(file2);
                    alert("Assigning sections to students");
                    Queries.assignSectionToStudents(1);
                    alert("Creating initail schedule");
                    Queries.createInitialStudentSchedule();
                    Reset.uploadStudentFile(1);
                }
                JOptionPane.showMessageDialog(null, "File uploaded successfuly!");
                Reset.uploadStudentFile(1);
            } else {
                alert("File not uploaded");
            }
        } else {
            Reset.resetStudents();
            JFileChooser chooser = new JFileChooser("/");
            int f = chooser.showSaveDialog(null);
            if (f == JFileChooser.APPROVE_OPTION) {
                String file = chooser.getSelectedFile().getAbsolutePath();
//                String[] split = file.split(".");
//                String extension = split[split.length - 1];
//                System.out.println(file);
//                if (!extension.equalsIgnoreCase("csv")) {
//                    alert("Please select a .csv file");
//                    return;
//                }
                System.out.println(file);
                File file2 = new File(file);
                JOptionPane.showMessageDialog(null, "It might take a while. Please have patient");
                Queries.addStudentsToDB(file2);
                Queries.assignSectionToStudents(1);
                Queries.createInitialStudentSchedule();
                Reset.uploadStudentFile(1);
            }
            JOptionPane.showMessageDialog(null, "File uploaded successfuly!");
            Reset.uploadStudentFile(1);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        next.setBackground(new Color(250, 250, 250));
        next.setForeground(new Color(0, 102, 153));
    }//GEN-LAST:event_nextMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    public static javax.swing.JLabel next;
    // End of variables declaration//GEN-END:variables
}
