/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.professor;

import Model.Queries;
import static db.DBConnection.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author muhammad awais 1
 */
public class add_professor_panel extends javax.swing.JPanel {

    /**
     * Creates new form add_professor_panel
     */
    public add_professor_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel96 = new javax.swing.JLabel();
        prof_id = new javax.swing.JTextField();
        jLabel94 = new javax.swing.JLabel();
        prof_name = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        addProfessorBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(0, 102, 153));
        jLabel96.setText("Professor Details:");
        add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 210, 30));

        prof_id.setForeground(new java.awt.Color(0, 102, 153));
        add(prof_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 360, 30));

        jLabel94.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(0, 102, 153));
        jLabel94.setText("Professor name:");
        add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 30));

        prof_name.setForeground(new java.awt.Color(0, 102, 153));
        add(prof_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 360, 30));

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(0, 102, 153));
        jLabel97.setText("Professor ID:");
        add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 210, 30));

        addProfessorBtn.setBackground(new java.awt.Color(0, 102, 153));
        addProfessorBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addProfessorBtn.setForeground(new java.awt.Color(255, 255, 255));
        addProfessorBtn.setText("add");
        addProfessorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfessorBtnActionPerformed(evt);
            }
        });
        add(addProfessorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 220, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void addProfessorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfessorBtnActionPerformed
        int profID = Integer.parseInt(prof_id.getText());
        String profName = prof_name.getText();
        Connection conn = getConnection();
        PreparedStatement stmt = null, stmt2 = null;

        String addProf = "insert into professor"
                + "("
                + "professor_id,"
                + "name"
                + ")"
                + " VALUES "
                + "(?, ?)";

        // add prof to db
        try {
            stmt = conn.prepareStatement(addProf);
            stmt.setInt(1, profID);
            stmt.setString(2, profName);
            stmt.execute();
            // get number of days and slots from db
            int days = Queries.getDaysCount();
            int slots = Queries.getSlotCount();
            // add empty professor schedule in db according to day and slot count
            String addTempSchedule = "insert into professor_schedule"
                    + "("
                    + "professor_id,"
                    + "day_no,"
                    + "timeslot_no,"
                    + "section_id,"
                    + "course_code,"
                    + "room_name,"
                    + "lecture_no,"
                    + "isLab"
                    + ")"
                    + " VALUES "
                    + "(?, ?, ?, ?, ?, ?, ?, ?)";
            for (int day = 1; day <= days; day++) {
                for (int slot = 1; slot <= slots; slot++) {
                    System.out.println(addProf);
                    System.out.println(addTempSchedule);
                    stmt2 = conn.prepareStatement(addTempSchedule);
                    stmt2.setInt(1, profID);
                    stmt2.setInt(2, day);
                    stmt2.setInt(3, slot);
                    stmt2.setString(4, "");
                    stmt2.setString(5, "");
                    stmt2.setString(6, "");
                    stmt2.setInt(7, 0);
                    stmt2.setString(8, "false");
                    stmt2.execute();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(add_professor_panel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_addProfessorBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProfessorBtn;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JTextField prof_id;
    private javax.swing.JTextField prof_name;
    // End of variables declaration//GEN-END:variables

}
