/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.student;

import Model.Queries;
import View.TableViewUtility;
import static db.DBConnection.createConnection;

/**
 *
 * @author muhammad awais 1
 */
public class view_all_students_panel extends javax.swing.JPanel {

    /**
     * Creates new form view_students_panel
     */
    public view_all_students_panel() {
        initComponents();
//        createConnection();
//        view_all_students_table.setModel(TableViewUtility.resultSetToTableModel(Queries.getAllStudent()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel106 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_all_students_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel106.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel106.setForeground(new java.awt.Color(0, 102, 153));
        jLabel106.setText("All students:");
        add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 26, 210, 40));

        view_all_students_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(view_all_students_table);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 660, 370));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel106;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable view_all_students_table;
    // End of variables declaration//GEN-END:variables
}
