/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.section;

/**
 *
 * @author muhammad awais 1
 */
public class add_new_program extends javax.swing.JPanel {

    /**
     * Creates new form add_new_program
     */
    public add_new_program() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel95 = new javax.swing.JLabel();
        roomname = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel97 = new javax.swing.JLabel();
        roomname1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(0, 102, 153));
        jLabel95.setText("Number of semesters:");
        add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 40));

        roomname.setForeground(new java.awt.Color(0, 102, 153));
        roomname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnameActionPerformed(evt);
            }
        });
        add(roomname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 470, 40));

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(0, 102, 153));
        jLabel96.setText("Add New Program Details:");
        add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 270, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("save program");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 230, 60));

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(0, 102, 153));
        jLabel97.setText("Program Title:");
        add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, 40));

        roomname1.setForeground(new java.awt.Color(0, 102, 153));
        roomname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomname1ActionPerformed(evt);
            }
        });
        add(roomname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 470, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void roomnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnameActionPerformed

    private void roomname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomname1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JTextField roomname;
    private javax.swing.JTextField roomname1;
    // End of variables declaration//GEN-END:variables
}
