package View.section;

import Model.Queries;
import static View.Alerts.alert;
import static View.Alerts.isEmpty;
//import static View.section.update_section_panel.	;
import static db.DBConnection.createConnection;
import static db.DBConnection.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static View.MainFrame.professor_course_allocation1;
import static View.MainFrame.create_section_panel1;

public class create_section_panel extends javax.swing.JPanel {

    public static ArrayList<String> selected_courses = new ArrayList<>();
    public static String section_id;

    public create_section_panel() {
        initComponents();
    }

    /**
     * 
     * @return ArrayList of all programs names
     */
    public static String[] getPrograms() {
        String[] programs = null;
        String q = "select program_name from program";
        createConnection();
        Connection conn = getConnection();
        PreparedStatement stmt = null;
        try {
            stmt = conn.prepareStatement(q);
            ResultSet rs = stmt.executeQuery();
            if (rs.last()) {
                int rows = rs.getRow();
                System.out.println(rows);
                programs = new String[rows];
                rs.beforeFirst();
            }
            int i = 0;
            while (rs.next()) {
                System.out.println(rs.getString(1));
                programs[i] = rs.getString(1);
                i++;
            }
            programs_dropdown.setModel(new DefaultComboBoxModel<>(programs));
        } catch (SQLException ex) {
            Logger.getLogger(create_section_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return programs;
    }

    public static String[] getCourses() {
        String[] courses = null;
        String q = "select * from course";
        createConnection();
        Connection conn = getConnection();
        PreparedStatement stmt = null;
        try {
            stmt = conn.prepareStatement(q);
            ResultSet rs = stmt.executeQuery();
            if (rs.last()) {
                int rows = rs.getRow();
                courses = new String[rows];
                rs.beforeFirst();
            }
            int i = 0;
            while (rs.next()) {
                courses[i] = rs.getString(2);
                i++;
            }
            courses_dropdown.setModel(new DefaultComboBoxModel<>(courses));
        } catch (SQLException ex) {
            Logger.getLogger(create_section_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return courses;
    }

    public static void fillSemesters() {
        // get selected program
        String selecte_program = programs_dropdown.getSelectedItem().toString();
        // get program id from database
        int program_id = 0;
        String q = "select program_id from program where program_name = '" + selecte_program + "'";
        Connection conn = getConnection();
        PreparedStatement stmt = null;
        try {
            stmt = conn.prepareStatement(q);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                program_id = rs.getInt(1);
            } else {
                JOptionPane.showMessageDialog(null, "Someting went wrong");
                return;
            }
            // get semesters of that program from semester table
            String[] semesters_list = null;
            q = "select * from semester where program_id = " + program_id;
            stmt = conn.prepareStatement(q);
            ResultSet semesters = stmt.executeQuery();
            if (semesters.last()) {
                int total_semesters = semesters.getRow();
                semesters.beforeFirst();
                semesters_list = new String[total_semesters];
            } else {
                JOptionPane.showMessageDialog(null, "Someting went wrong");
                return;
            }
            int i = 0;
            while (semesters.next()) {
                semesters_list[i] = semesters.getInt(1) + "";
                i++;
            }
            semesters_dropdown.setModel(new DefaultComboBoxModel<>(semesters_list));
        } catch (SQLException ex) {
            Logger.getLogger(create_section_panel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void updateTextArea() {
        String str = "Allocations:\n";
        for (String course: selected_courses) {
            str += "\n" + course;
        }
        assigned_courses.setText(str);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        semesters_dropdown = new javax.swing.JComboBox<>();
        programs_dropdown = new javax.swing.JComboBox<>();
        jLabel95 = new javax.swing.JLabel();
        section_ID = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel97 = new javax.swing.JLabel();
        capacity = new javax.swing.JTextField();
        create_section_btn = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        courses_dropdown = new javax.swing.JComboBox<>();
        addCourseButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        assigned_courses = new javax.swing.JTextArea();
        jLabel99 = new javax.swing.JLabel();
        section_name = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(0, 102, 153));
        jLabel96.setText("Program:");
        jPanel1.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 40));

        jLabel94.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel94.setForeground(new java.awt.Color(0, 102, 153));
        jLabel94.setText("Section ID:");
        jPanel1.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 40));

        semesters_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(semesters_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 370, 40));

        programs_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        programs_dropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                programs_dropdownItemStateChanged(evt);
            }
        });
        programs_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programs_dropdownActionPerformed(evt);
            }
        });
        jPanel1.add(programs_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 370, 40));

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(0, 102, 153));
        jLabel95.setText("Semester:");
        jPanel1.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 40));

        section_ID.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(section_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 370, 40));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 640, 10));

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(0, 102, 153));
        jLabel97.setText("Section Capacity:");
        jPanel1.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 210, 40));

        capacity.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(capacity, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 370, 40));

        create_section_btn.setBackground(new java.awt.Color(0, 102, 153));
        create_section_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        create_section_btn.setForeground(new java.awt.Color(255, 255, 255));
        create_section_btn.setText("NEXT");
        create_section_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_section_btnActionPerformed(evt);
            }
        });
        jPanel1.add(create_section_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 760, 160, 60));

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(0, 102, 153));
        jLabel60.setText("Assign courses to section:");
        jPanel1.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, -1));

        jLabel98.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(0, 102, 153));
        jLabel98.setText("Course:");
        jPanel1.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 90, 30));

        courses_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"" }));
        jPanel1.add(courses_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 380, 40));

        addCourseButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addCourseButton.setForeground(new java.awt.Color(0, 102, 153));
        addCourseButton.setText("Assign");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addCourseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 80, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 630, 20));

        assigned_courses.setEditable(false);
        assigned_courses.setColumns(20);
        assigned_courses.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        assigned_courses.setForeground(new java.awt.Color(0, 102, 153));
        assigned_courses.setRows(5);
        assigned_courses.setText("Courses that are assigned to the section will be printed here\n");
        assigned_courses.setDisabledTextColor(new java.awt.Color(250, 250, 250));
        assigned_courses.setEnabled(false);
        jScrollPane2.setViewportView(assigned_courses);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 630, 150));

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(0, 102, 153));
        jLabel99.setText("Section Name:");
        jPanel1.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 40));

        section_name.setForeground(new java.awt.Color(0, 102, 153));
        jPanel1.add(section_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 370, 40));

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 690, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        if (!selected_courses.remove(courses_dropdown.getSelectedItem().toString())) {
            selected_courses.add(courses_dropdown.getSelectedItem().toString());
        }
        updateTextArea();
    }//GEN-LAST:event_addCourseButtonActionPerformed
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void programs_dropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_programs_dropdownItemStateChanged
        fillSemesters();
    }//GEN-LAST:event_programs_dropdownItemStateChanged

    private void create_section_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_section_btnActionPerformed
        Connection conn = getConnection();
        PreparedStatement stmt = null;
        String programName = programs_dropdown.getSelectedItem().toString();
        String sectionID = section_ID.getText();
        section_id = section_ID.getText();
        String sectionName = section_name.getText();
        int semester = 0, cpacity;
        int programID = Queries.getProgramID(programName);
        // Frontend validation
        if (isEmpty(sectionID)) {
            alert("Please Enter Section ID");
            return;
        }
        if (isEmpty(sectionName)) {
            alert("Please Enter Section Name");
            return;
        }
        if (selected_courses.size() < 4) {
            JOptionPane.showMessageDialog(null, "Please select at least three courses");
            return;
        }
        // create section
        String create_section_query = "insert into section "
                + "("
                + "section_id,"
                + "name,"
                + "semester_no,"
                + "program_id,"
                + "student_strength"
                + ")"
                + " VALUES "
                + "(?, ?, ?, ?, ?)";
        try {
            cpacity = Integer.parseInt(capacity.getText());
            semester = Integer.parseInt(semesters_dropdown.getSelectedItem().toString());
            stmt = conn.prepareStatement(create_section_query);
            stmt.setString(1, sectionID);
            stmt.setString(2, sectionName);
            stmt.setInt(3, semester);
            stmt.setInt(4, programID);
            stmt.setInt(5, cpacity);
            stmt.execute();
            //  add selected courses
            for (String selectedCourse : selected_courses) {
                String q = "insert into section_courses"
                        + "("
                        + "section_id,"
                        + "course_code"
                        + ")"
                        + " VALUES "
                        + "(?, ?)";
                stmt = conn.prepareStatement(q);
                stmt.setString(1, sectionID);
                stmt.setString(2, Queries.getCourseCode(selectedCourse));
                stmt.execute();
                assigned_courses.append("\n" + selectedCourse);
            }
            // generate temp schedule
            int days = Queries.getDaysCount();
            int slots = Queries.getSlotCount();
            // add empty section schedule in db according to day and slot count
            String addTempSchedule = "insert into section_schedule"
                    + "(section_id,\n"
                    + "day_no,\n"
                    + "timeslot_no,\n"
                    + "course_code,\n"
                    + "room_name,\n"
                    + "lecture_no,\n"
                    + "isLab)"
                    + " VALUES "
                    + "(?, ?, ?, ?, ?, ?, ?)";
            for (int day = 1; day <= days; day++) {
                for (int slot = 1; slot <= slots; slot++) {
                    stmt = conn.prepareStatement(addTempSchedule);
                    stmt.setString(1, sectionID);
                    stmt.setInt(2, day);
                    stmt.setInt(3, slot);
                    stmt.setString(4, "");
                    stmt.setString(5, "");
                    stmt.setInt(6, 0);
                    stmt.setString(7, "false");
                    stmt.execute();
                }
            }
            JOptionPane.showMessageDialog(null, "Section data added successfully!");
            assigned_courses.setText("");
            capacity.setText("");
            section_ID.setText("");
            section_name.setText("");
            Professor_course_allocation.displaySectionID(sectionID);
            Professor_course_allocation.displayProfessors(Queries.getAllProfessors());
            Professor_course_allocation.displayCourses(selected_courses);
            professor_course_allocation1.setVisible(true);
            create_section_panel1.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(create_section_panel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Semester number or Capacity is invalid!");
        }
    }//GEN-LAST:event_create_section_btnActionPerformed

    private void programs_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programs_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_programs_dropdownActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        professor_course_allocation1.setVisible(true);
        create_section_panel1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    static javax.swing.JTextArea assigned_courses;
    private javax.swing.JTextField capacity;
    private static javax.swing.JComboBox<String> courses_dropdown;
    private javax.swing.JButton create_section_btn;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private static javax.swing.JComboBox<String> programs_dropdown;
    private javax.swing.JTextField section_ID;
    private javax.swing.JTextField section_name;
    private static javax.swing.JComboBox<String> semesters_dropdown;
    // End of variables declaration//GEN-END:variables
}
