/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.section;

/**
 *
 * @author muhammad awais 1
 */
public class Professor_course_allocation extends javax.swing.JPanel {

    /** Creates new form Professor_course_allocation */
    public Professor_course_allocation() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        checkBox1 = new javax.swing.JCheckBox();
        checkBox2 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jComboBox9 = new javax.swing.JComboBox<>();
        roomname = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        roomname1 = new javax.swing.JTextField();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        roomname2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(32767, 35000));
        setPreferredSize(new java.awt.Dimension(409, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 102, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("Allocations:");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 860, 170));

        jLabel95.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel95.setForeground(new java.awt.Color(0, 102, 153));
        jLabel95.setText("Assign Professors to section courses:");
        jPanel1.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 370, 40));

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel96.setForeground(new java.awt.Color(0, 102, 153));
        jLabel96.setText("Professor:");
        jPanel1.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 160, 40));

        checkBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBox1.setForeground(new java.awt.Color(0, 102, 153));
        checkBox1.setText("Lecture");
        jPanel1.add(checkBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 110, 30));

        checkBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBox2.setForeground(new java.awt.Color(0, 102, 153));
        checkBox2.setText("Lab");
        jPanel1.add(checkBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 70, 30));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 102, 153));
        jRadioButton1.setText("Both");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 70, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("save allocations");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 230, 60));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"" }));
        jPanel1.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 210, 40));

        roomname.setForeground(new java.awt.Color(0, 102, 153));
        roomname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomnameActionPerformed(evt);
            }
        });
        jPanel1.add(roomname, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 220, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 153));
        jButton8.setText("specify");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 80, 30));

        roomname1.setForeground(new java.awt.Color(0, 102, 153));
        roomname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomname1ActionPerformed(evt);
            }
        });
        jPanel1.add(roomname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 480, 40));

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel101.setForeground(new java.awt.Color(0, 102, 153));
        jLabel101.setText("All Courses:");
        jPanel1.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 150, 40));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(0, 102, 153));
        jLabel102.setText("Section:");
        jPanel1.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, 40));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"" }));
        jPanel1.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 210, 40));

        roomname2.setForeground(new java.awt.Color(0, 102, 153));
        roomname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomname2ActionPerformed(evt);
            }
        });
        jPanel1.add(roomname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 220, 40));

        jScrollPane2.setViewportView(jPanel1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 950, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void roomnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomnameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void roomname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomname1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        if(jRadioButton1.isSelected()){
            checkBox1.setSelected(true);
            checkBox2.setSelected(true);
        }
        else if (!jRadioButton1.isSelected()){
            checkBox1.setSelected(false);
            checkBox2.setSelected(false);            
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void roomname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomname2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox1;
    private javax.swing.JCheckBox checkBox2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField roomname;
    private javax.swing.JTextField roomname1;
    private javax.swing.JTextField roomname2;
    // End of variables declaration//GEN-END:variables

}
