/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.section;

/**
 *
 * @author muhammad awais 1
 */
public class remove_section_panel extends javax.swing.JPanel {

    /**
     * Creates new form remove_section_panel
     */
    public remove_section_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel99 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel99.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel99.setForeground(new java.awt.Color(0, 102, 153));
        jLabel99.setText("Remove Section Panel:");
        add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 300, 40));

        jLabel102.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(0, 102, 153));
        jLabel102.setText("Section:");
        add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 150, 40));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"" }));
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 460, 40));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("remove section");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 230, 60));

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 102, 153));
        jTextArea3.setRows(5);
        jTextArea3.setText("Print all Details of the section here\n\n");
        jScrollPane4.setViewportView(jTextArea3);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 630, 150));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
