/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package live_tiling;

/**
 *
 * @author ACER
 */
public class Tiling extends javax.swing.JPanel {

    /**
     * Creates new form Tiling
     */
    public Tiling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tilingScrollPane = new javax.swing.JScrollPane();
        tilingPane = new javax.swing.JPanel();

        javax.swing.GroupLayout tilingPaneLayout = new javax.swing.GroupLayout(tilingPane);
        tilingPane.setLayout(tilingPaneLayout);
        tilingPaneLayout.setHorizontalGroup(
            tilingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        tilingPaneLayout.setVerticalGroup(
            tilingPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 359, Short.MAX_VALUE)
        );

        tilingScrollPane.setViewportView(tilingPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tilingScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tilingScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel tilingPane;
    public static javax.swing.JScrollPane tilingScrollPane;
    // End of variables declaration//GEN-END:variables
}
