/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.datesheet_generation;

/**
 *
 * @author Muhammad Awais
 */
public class main_panel extends javax.swing.JPanel {

    /**
     * Creates new form main_panel
     */
    public main_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_panel1 = new View.datesheet_generation.title_panel();
        first_panel1 = new View.datesheet_generation.first_panel();
        second_panel1 = new View.datesheet_generation.second_panel();
        third_panel1 = new View.datesheet_generation.third_panel();
        fourth_panel1 = new View.datesheet_generation.fourth_panel();
        fifth_panel1 = new View.datesheet_generation.fifth_panel();

        setBackground(new java.awt.Color(50, 50, 50));
        setLayout(new java.awt.CardLayout());
        add(title_panel1, "card7");
        add(first_panel1, "card2");
        add(second_panel1, "card3");
        add(third_panel1, "card4");
        add(fourth_panel1, "card5");
        add(fifth_panel1, "card6");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static View.datesheet_generation.fifth_panel fifth_panel1;
    public static View.datesheet_generation.first_panel first_panel1;
    public static View.datesheet_generation.fourth_panel fourth_panel1;
    public static View.datesheet_generation.second_panel second_panel1;
    public static View.datesheet_generation.third_panel third_panel1;
    public static View.datesheet_generation.title_panel title_panel1;
    // End of variables declaration//GEN-END:variables
}
