/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.datesheet_generation;

import java.awt.Color;

/**
 *
 * @author Muhammad Awais
 */
public class second_panel extends javax.swing.JPanel {

    /**
     * Creates new form second_panel
     */
    public second_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        next = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        time_duration = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(50, 50, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        back.setForeground(new java.awt.Color(0, 102, 153));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setText("<- B a c k");
        back.setToolTipText("Logo");
        back.setAlignmentX(0.5F);
        back.setAutoscrolls(true);
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });
        add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 200, 60));

        next.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        next.setForeground(new java.awt.Color(0, 102, 153));
        next.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        next.setText("N e x t ->");
        next.setToolTipText("Logo");
        next.setAlignmentX(0.5F);
        next.setAutoscrolls(true);
        next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextMouseExited(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 200, 60));

        jLabel109.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 255, 255));
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("E x a m   D u r a t i o n");
        add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, 70));

        time_duration.setBackground(new java.awt.Color(50, 50, 50));
        time_duration.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        time_duration.setForeground(new java.awt.Color(255, 255, 255));
        time_duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "60","90","120","150","180" }));
        time_duration.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                time_durationItemStateChanged(evt);
            }
        });
        time_duration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time_durationActionPerformed(evt);
            }
        });
        add(time_duration, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 560, 40));

        jTextField1.setBackground(new java.awt.Color(50, 50, 50));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 430, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        main_panel.second_panel1.setVisible(false);
        main_panel.first_panel1.setVisible(true); 
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setBackground(new Color(0, 102, 153));
        back.setForeground(new Color(250, 250, 250));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setBackground(new Color(250, 250, 250));
        back.setForeground(new Color(0, 102, 153));
    }//GEN-LAST:event_backMouseExited

    private void nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseClicked
        main_panel.second_panel1.setVisible(false);
        main_panel.third_panel1.setVisible(true); 
//      show JOptionPane confirmation panel
    }//GEN-LAST:event_nextMouseClicked

    private void nextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseEntered
        next.setBackground(new Color(0, 102, 153));
        next.setForeground(new Color(250, 250, 250));
    }//GEN-LAST:event_nextMouseEntered

    private void nextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextMouseExited
        next.setBackground(new Color(250, 250, 250));
        next.setForeground(new Color(0, 102, 153));
    }//GEN-LAST:event_nextMouseExited

    private void time_durationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_time_durationItemStateChanged
       
    }//GEN-LAST:event_time_durationItemStateChanged

    private void time_durationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time_durationActionPerformed
        jTextField1.setText(time_duration.getSelectedItem().toString()+"  Minutes");
    }//GEN-LAST:event_time_durationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel back;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JTextField jTextField1;
    public static javax.swing.JLabel next;
    public static javax.swing.JComboBox<String> time_duration;
    // End of variables declaration//GEN-END:variables
}
