/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.viewtimetable_panel;

/**
 *
 * @author Muhammad Awais
 */
public class Clash_resolving_panel extends javax.swing.JPanel {

    /**
     * Creates new form Clash_resolving_panel
     */
    public Clash_resolving_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        entity_name = new javax.swing.JLabel();
        entity_name1 = new javax.swing.JLabel();
        entity_name2 = new javax.swing.JLabel();
        entity_name3 = new javax.swing.JLabel();
        entity_name4 = new javax.swing.JLabel();
        entity_name5 = new javax.swing.JLabel();
        entity_name6 = new javax.swing.JLabel();
        entity_name7 = new javax.swing.JLabel();
        entity_name8 = new javax.swing.JLabel();
        entity_name9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 50, 50));

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entity_name.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name.setForeground(new java.awt.Color(255, 255, 255));
        entity_name.setText("Status");
        jPanel1.add(entity_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 180, 40));

        entity_name1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name1.setForeground(new java.awt.Color(255, 255, 255));
        entity_name1.setText("Professor name:");
        jPanel1.add(entity_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 310, 40));

        entity_name2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name2.setForeground(new java.awt.Color(255, 255, 255));
        entity_name2.setText("Free slot not found");
        jPanel1.add(entity_name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 220, 40));

        entity_name3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name3.setForeground(new java.awt.Color(255, 255, 255));
        entity_name3.setText("Professor name:");
        jPanel1.add(entity_name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 220, 40));

        entity_name4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name4.setForeground(new java.awt.Color(255, 255, 255));
        entity_name4.setText("Room name:");
        jPanel1.add(entity_name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 220, 40));

        entity_name5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name5.setForeground(new java.awt.Color(255, 255, 255));
        entity_name5.setText("Room name:");
        jPanel1.add(entity_name5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 310, 40));

        entity_name6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name6.setForeground(new java.awt.Color(255, 255, 255));
        entity_name6.setText("Section name:");
        jPanel1.add(entity_name6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 310, 40));

        entity_name7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name7.setForeground(new java.awt.Color(255, 255, 255));
        entity_name7.setText("Section name:");
        jPanel1.add(entity_name7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 220, 40));

        entity_name8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name8.setForeground(new java.awt.Color(255, 255, 255));
        entity_name8.setText("Free slot found");
        jPanel1.add(entity_name8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 220, 40));

        entity_name9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        entity_name9.setForeground(new java.awt.Color(255, 255, 255));
        entity_name9.setText("Free slot not found");
        jPanel1.add(entity_name9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 220, 40));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 934, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel entity_name;
    public static javax.swing.JLabel entity_name1;
    public static javax.swing.JLabel entity_name2;
    public static javax.swing.JLabel entity_name3;
    public static javax.swing.JLabel entity_name4;
    public static javax.swing.JLabel entity_name5;
    public static javax.swing.JLabel entity_name6;
    public static javax.swing.JLabel entity_name7;
    public static javax.swing.JLabel entity_name8;
    public static javax.swing.JLabel entity_name9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
