/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.viewtimetable_panel;

import java.awt.Color;

/**
 *
 * @author Muhammad Awais
 */
public class clash_resolving_frame extends javax.swing.JFrame {

    /**
     * Creates new form clash_resolving_frame
     */
    public clash_resolving_frame() {
        initComponents();
        getContentPane().setBackground(new Color(50,50,50)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_up_window_for_viewing_details_of_clash1 = new View.viewtimetable_panel.Pop_up_window_for_viewing_details_of_clash();
        clash_resolving_panel1 = new View.viewtimetable_panel.Clash_resolving_panel();

        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(pop_up_window_for_viewing_details_of_clash1, "card3");

        javax.swing.GroupLayout clash_resolving_panel1Layout = new javax.swing.GroupLayout(clash_resolving_panel1);
        clash_resolving_panel1.setLayout(clash_resolving_panel1Layout);
        clash_resolving_panel1Layout.setHorizontalGroup(
            clash_resolving_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        clash_resolving_panel1Layout.setVerticalGroup(
            clash_resolving_panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        getContentPane().add(clash_resolving_panel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clash_resolving_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clash_resolving_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clash_resolving_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clash_resolving_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clash_resolving_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private View.viewtimetable_panel.Clash_resolving_panel clash_resolving_panel1;
    private View.viewtimetable_panel.Pop_up_window_for_viewing_details_of_clash pop_up_window_for_viewing_details_of_clash1;
    // End of variables declaration//GEN-END:variables
}
