/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.viewtimetable_panel;

import Model.Course;
import Model.Queries;
import View.TableViewUtility;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import schedule.DisplayTable;
import schedule.DisplayTemplate;
import schedule.Template2;

/**
 *
 * @author muhammad awais 1
 */
public class search_for_specific_entity extends javax.swing.JPanel {

    /**
     * Creates new form search_for_specific_entity
     */
    public search_for_specific_entity() {
        initComponents();
    }
    
    public static void setDropdownData(String[] data) {
        general_dropdown.setModel(new DefaultComboBoxModel<>(data));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entity_name_lbl = new javax.swing.JLabel();
        general_dropdown = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_textarea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        schedule_table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entity_name_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entity_name_lbl.setForeground(new java.awt.Color(0, 102, 153));
        entity_name_lbl.setText("Entity:");
        add(entity_name_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 40));

        general_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        general_dropdown.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                general_dropdownItemStateChanged(evt);
            }
        });
        general_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                general_dropdownActionPerformed(evt);
            }
        });
        add(general_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 420, 40));

        result_textarea.setColumns(20);
        result_textarea.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        result_textarea.setForeground(new java.awt.Color(0, 102, 153));
        result_textarea.setRows(5);
        result_textarea.setText("Search Results \ndisplay constraints of entity\n");
        jScrollPane1.setViewportView(result_textarea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 700, 110));

        schedule_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(schedule_table);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 740, 410));
    }// </editor-fold>//GEN-END:initComponents

    private void general_dropdownItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_general_dropdownItemStateChanged
        String stat = entity_name_lbl.getText();
        String value = general_dropdown.getSelectedItem().toString();
        ResultSet rs;
        if (stat.startsWith("Professor")) {
            int profID = Queries.getProfessorID(value);
            rs = Queries.getSectionScheduleRS("professor_schedule", "professor_id", profID + "");
            schedule_table.setModel(TableViewUtility.resultSetToTableModel(rs));
        } else if (stat.startsWith("Student")) {
            String studentSchedule = "select \n"
                    + "student_registration_no as Student, \n"
                    + "section_id as Section,\n"
                    + "name as Day, course_code as Course,\n"
                    + "starting_time as StartTime,\n"
                    + "ending_time as EndTime, \n"
                    + "room_name as Room\n"
                    + "from "
                    + "student_schedule join day using (day_no)"
                    + " join timeslot using (timeslot_no) "
                    + "where "
                    + "student_registration_no = '" + value + "'";
            
            rs = Queries.getRS(studentSchedule);
            schedule_table.setModel(TableViewUtility.resultSetToTableModel(rs));
        } else if (stat.startsWith("Section")) {
            dt.DisplayOneTable(value);
            dt.getFrame().setVisible(true);
//            dt.setVisible(true);
            // get section professor allocation
//            ResultSet professorSectionAllocation = Queries.getSectionProfessorAllocation(value);
//            try {
//                String str = "";
//                while (professorSectionAllocation.next()) {
//                    String courseCode = professorSectionAllocation.getString("course_code");
//                    ResultSet course = Queries.getCourseDetails(courseCode);
//                    if (course.next()) {
//                        str += course.getString("title");
//                    }
//                    int professorID = professorSectionAllocation.getInt("professor_id");
//                    String professorName = Queries.getProfessorName(professorID);
//                    str += "\t" + professorName;
//                    str += "\t" + professorSectionAllocation.getString("lab_or_theory");
//                    str += "\n";
//                }
//                result_textarea.setText(str);
//            } catch (SQLException ex) {
//                Logger.getLogger(search_for_specific_entity.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            rs = Queries.getFinalSectionSchedule(value);
//            schedule_table.setModel(TableViewUtility.resultSetToTableModel(rs));

        } else if (stat.startsWith("Room")) {
            rs = Queries.getSectionScheduleRS("room_availabilty", "room_name", value + "");
            schedule_table.setModel(TableViewUtility.resultSetToTableModel(rs));
        }
    }//GEN-LAST:event_general_dropdownItemStateChanged

    private void general_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_general_dropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_general_dropdownActionPerformed
    
    DisplayTable dt = new DisplayTable();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel entity_name_lbl;
    private static javax.swing.JComboBox<String> general_dropdown;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    static javax.swing.JTextArea result_textarea;
    private javax.swing.JTable schedule_table;
    // End of variables declaration//GEN-END:variables
}
