/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.viewtimetable_panel;

/**
 *
 * @author muhammad awais 1
 */
public class View_all_clashes_panel extends javax.swing.JPanel {

    /**
     * Creates new form details_of_clash
     */
    public View_all_clashes_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel109 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        entity_name = new javax.swing.JLabel();
        info_lbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel109.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(0, 102, 153));
        jLabel109.setText("Clash Details Panel:");
        add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 290, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 680, 310));

        entity_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        entity_name.setForeground(new java.awt.Color(0, 102, 153));
        entity_name.setText("Professor-wise/Student-wise");
        add(entity_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 40));

        info_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        info_lbl.setForeground(new java.awt.Color(0, 102, 153));
        info_lbl.setText("double click on row to view details (pop-up window)");
        add(info_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, 480, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel entity_name;
    public static javax.swing.JLabel info_lbl;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
